# Generated by Django 2.2 on 2019-06-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190602_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lists',
            new_name='list',
        ),
    ]
