# Generated by Django 2.2 on 2019-06-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190602_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_lvl',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'green'), (2, 'yellow'), (3, 'red')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
