# Generated by Django 2.2 on 2019-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190602_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
