# Generated by Django 2.2 on 2019-06-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_planned_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
    ]
