# Generated by Django 2.1.3 on 2018-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default_avatar/default.png', upload_to='profile_images'),
        ),
    ]
